### ISSUE TITLE
Clean up after itself if it triggers any handled errors

### ISSUE THREAD

**Issue by alex-e-leon** [jesstelford/version-changelog#1]
I tried to run it before hooking up a repository to git, and got the `[WARN]: Unable to determine origin URL for adding to changelog` but it left my repo in a changed state. Would be nice if it cleaned up after itself instead.

**Comment by jesstelford** [comment]
Excellent point! Fix published in [2.0.0](https://github.com/jesstelford/version-changelog/blob/master/CHANGELOG.md#200---2016-10-25)
