### ISSUE TITLE
Unnecessary '[]' after version

### ISSUE THREAD

**Issue by AlexK-IL** [jesstelford/version-changelog#5]
It seems that you add unnecessary `[]` characters after each version.  
For example:
```
## [1.0.0][]
```
Is there a reason for there or is it a bug?  
Just was curious since it doesn't adhere to keepachangelog.com.  
Also wanted to say that I love this tool, thank you for creating it!

**Comment by jesstelford** [comment]
Hey @AlexK-IL, glad you like it!

The `[something][]` syntax is a way in markdown to specify a URL later in the document, called an _implicit link name_: https://daringfireball.net/projects/markdown/syntax#link

> The point of reference-style links is not that they’re easier to write. The point is that with reference-style links, your document source is vastly more readable. Compare the above examples: using reference-style links, the paragraph itself is only 81 characters long; with inline-style links, it’s 176 characters; and as raw HTML, it’s 234 characters. In the raw HTML, there’s more markup than there is text.
> 
> With Markdown’s reference-style links, a source document much more closely resembles the final output, as rendered in a browser. By allowing you to move the markup-related metadata out of the paragraph, you can add links without interrupting the narrative flow of your prose.
