### ISSUE TITLE
Supporting ssh gitlab remote urls

### ISSUE THREAD

**Issue by AlexK-IL** [jesstelford/version-changelog#6]
I'm using gitlab with an ssh remote url and it seems that the function `githubUrlFromGit` returns `undefined`.  
Any way to fix it?

**Comment by jesstelford** [comment]
Now that https://github.com/jesstelford/version-changelog/pull/10 is merged, it should be easier to add gitlab support. PRs welcome!

**Comment by jesstelford** [comment]
I went ahead and added gitlab support. It's now available in `v3.1.0`, to use it, you'll need to add the `--remote=gitlab` CLI switch:

```
version-changelog --remote=gitlab ./CHANGELOG.md
```
